/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as ApiPublicPaykassaRouteImport } from './routes/api/public/paykassa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaykassaRoute = ApiPublicPaykassaRouteImport.update({
  id: '/api/public/paykassa',
  path: '/api/public/paykassa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/deposit': typeof DepositRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/withdraw': typeof WithdrawRoute
  '/api/public/paykassa': typeof ApiPublicPaykassaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/deposit': typeof DepositRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/withdraw': typeof WithdrawRoute
  '/api/public/paykassa': typeof ApiPublicPaykassaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/deposit': typeof DepositRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/withdraw': typeof WithdrawRoute
  '/api/public/paykassa': typeof ApiPublicPaykassaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/admin'
    | '/community'
    | '/deposit'
    | '/referrals'
    | '/rewards'
    | '/withdraw'
    | '/api/public/paykassa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/admin'
    | '/community'
    | '/deposit'
    | '/referrals'
    | '/rewards'
    | '/withdraw'
    | '/api/public/paykassa'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/admin'
    | '/community'
    | '/deposit'
    | '/referrals'
    | '/rewards'
    | '/withdraw'
    | '/api/public/paykassa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  AdminRoute: typeof AdminRoute
  CommunityRoute: typeof CommunityRoute
  DepositRoute: typeof DepositRoute
  ReferralsRoute: typeof ReferralsRoute
  RewardsRoute: typeof RewardsRoute
  WithdrawRoute: typeof WithdrawRoute
  ApiPublicPaykassaRoute: typeof ApiPublicPaykassaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paykassa': {
      id: '/api/public/paykassa'
      path: '/api/public/paykassa'
      fullPath: '/api/public/paykassa'
      preLoaderRoute: typeof ApiPublicPaykassaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  AdminRoute: AdminRoute,
  CommunityRoute: CommunityRoute,
  DepositRoute: DepositRoute,
  ReferralsRoute: ReferralsRoute,
  RewardsRoute: RewardsRoute,
  WithdrawRoute: WithdrawRoute,
  ApiPublicPaykassaRoute: ApiPublicPaykassaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
